Выполнение ТЗ 8-го спринта
ovcharovaao/java-kanban pull request #3
Opened 2024-08-26 10:41 UTC by ovcharovaao

2024-08-26 20:15 UTC, andrew-larkin requested changes
Привет! Отличная работа, очень качественная реализация нового функционала - по нему нет вопросов. В одном месте добавить конструктор - он нам понадобится в следующем спринте - и работа будет принята.

2024-08-26 20:15 UTC, andrew-larkin commented on src/tasks/Subtask.java
> +    public Subtask(String name, String description, int epicID, LocalDateTime startTime, Duration duration) {
надо добавить здесь конструктор, который принимает 3 параметра как это было раньше

2024-08-26 20:51 UTC, ovcharovaao commented on src/tasks/Subtask.java
> +    public Subtask(String name, String description, int epicID, LocalDateTime startTime, Duration duration) {
Вернула прежний конструктор

2024-08-27 18:23 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-08-27 18:25 UTC, merged